name: gucy
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  badges: ^3.1.2
  cloud_firestore: ^4.13.3
  firebase_core: ^2.24.0
  flutter:
    sdk: flutter
  flutter_slidable: ^0.6.0
  flutter_phone_direct_caller: ^2.1.0
  url_launcher: ^6.1.5
  go_router: ^12.1.1
  intl: ^0.18.1
  password_strength_checker: ^1.2.2
  provider: ^6.1.1
  flutter_native_splash: ^2.0.1+1
  firebase_auth: ^4.15.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_rating_bar: ^4.0.1

flutter_native_splash:
  color: "#ffffff"
  image: assets/logo.png
  android: true
  ios: true
  image_size: "300x300"

flutter:
  uses-material-design: true
  assets:
    - assets/
