name: gucy
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_slidable: ^0.6.0  
  flutter_phone_direct_caller: ^2.1.0 
  url_launcher: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_rating_bar: ^4.0.1

flutter:
  uses-material-design: true
