name: gucy
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  badges: ^3.1.2
  cloud_firestore: ^4.13.3
  firebase_core: ^2.24.0
  flutter:
    sdk: flutter
  flutter_slidable: ^0.6.0
  flutter_phone_direct_caller: ^2.1.0
  url_launcher: ^6.1.5
  go_router: ^12.1.1
  intl: ^0.18.1
  password_strength_checker: ^1.2.2
  provider: ^6.1.1
  flutter_native_splash: ^2.0.1+1
  firebase_auth: ^4.15.3
  flutter_svg: ^2.0.9
  image_picker: ^1.0.5
  firebase_storage: ^11.5.6
  path: ^1.8.3
  firebase_core_platform_interface:
  firebase_messaging: ^14.7.9
  flex_color_picker: ^3.3.0
  shared_preferences: ^2.2.2
  flutter_launcher_icons: ^0.13.1
  share_plus: ^7.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_rating_bar: ^4.0.1

flutter_native_splash:
  background_image: "assets/icon/icon-background.png"
  image: "assets/icon/icon.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icon/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "assets/icon/icon-background.png"
  adaptive_icon_foreground: "assets/icon/icon.png" # android min sdk min:16, default 21
  # web:
  #   generate: true
  #   image_path: "path/to/image.png"
  #   background_color: "#hexcode"
  #   theme_color: "#hexcode"
  # windows:
  #   generate: true
  #   image_path: "path/to/image.png"
  #   icon_size: 48 # min:48, max:256, default: 48
  # macos:
  #   generate: true
  #   image_path: "path/to/image.png"
