// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtkmLSt3ADlWTx9SqqLvHaEG4ksayayUk',
    appId: '1:527400651671:web:ea3a51a89e08eac4fbd2d2',
    messagingSenderId: '527400651671',
    projectId: 'gucy-45427',
    authDomain: 'gucy-45427.firebaseapp.com',
    databaseURL: 'https://gucy-45427-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'gucy-45427.appspot.com',
    measurementId: 'G-EGW2WTMDS4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm_TY8TD13vYnYxB_Zsfx4xJJtCeTiJ9M',
    appId: '1:527400651671:android:0eff33db483e9a6efbd2d2',
    messagingSenderId: '527400651671',
    projectId: 'gucy-45427',
    databaseURL: 'https://gucy-45427-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'gucy-45427.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWoKPvR9n7fyNUMHEzdMwL5of7gx6H06o',
    appId: '1:527400651671:ios:dd7807aeb89bbce6fbd2d2',
    messagingSenderId: '527400651671',
    projectId: 'gucy-45427',
    databaseURL: 'https://gucy-45427-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'gucy-45427.appspot.com',
    iosBundleId: 'com.fouram.gucy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWoKPvR9n7fyNUMHEzdMwL5of7gx6H06o',
    appId: '1:527400651671:ios:edc3e524b47ae8e3fbd2d2',
    messagingSenderId: '527400651671',
    projectId: 'gucy-45427',
    databaseURL: 'https://gucy-45427-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'gucy-45427.appspot.com',
    iosBundleId: 'com.fouram.gucy.RunnerTests',
  );
}
